sonar.projectKey=account-app
sonar.projectName=account-app
sonar.projectVersion=1.0
sonar.sources=src
sonar.login=sqp_2a98cba6fce5e4b52e975797a1adcea7e31c2239
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=http://127.0.0.1:9000